### ISSUE TITLE
`updateNotificationConfig` logging escaping keeps growing...

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/notify#253]
## Describe the bug

When updating a notification config, it appears the escaping from the previous config object isn't parsed, and so those escape characters are then escaped again on the next save...

Not a big issue, just clogging the logs:

![Screenshot 2023-11-20 at 12 04 09 PM](https://github.com/msupply-foundation/notify/assets/55115239/7d88bff8-f814-4cb2-8360-6576a2e4c05c)

## To Reproduce

Steps to reproduce the behaviour:

1. Go to Notifications
2. Click on Create a new Scheduled notification
3. Update and save it several times
4. View logs for growing escapes

## Expected behaviour

Singular escapation :)

**Comment by jmbrunskill** [comment]
I've seen this too actually. Forgot to raise an issue, great thing to fix.
