### ISSUE TITLE
Cold chain: Notification wording

### ISSUE THREAD

**Issue by adamdewey** [msupply-foundation/notify#268]
## Is your feature request related to a problem? Please describe

This issue is to try to clarify the cold chain notification titles. 

We have 3 types of cold chain event that we are notifying on: 

- High temperature
- Low temperature
- No data coming through
The preferred wording would be: 

### Temperature excursions

**Title**
🔥 `High temperature alert!`
❄️ `Low temperature alert!`

**Location**
`Facility: X`
`Location: Y`
`Sensor: Z`

**Datetime**
`Date: DD MMM YYYY`
`Time: HH:mm`

**Temperature**
`Temperature: X.YZ °C`

### Monitoring connection

**Title**
📶 `Monitoring connection lost!`

**Location**
`Facility: X`
`Location: Y`
`Sensor: Z`

**Datetime**
`Date: DD MMM YYYY`
`Time: HH:mm`

**Duration**
`Last data received: X minutes ago`

### Resolved alerts

**Title**
✅ `Alert resolved`

**Location**
`Facility: X`
`Location: Y`
`Sensor: Z`

**Datetime**
`Date: DD MMM YYYY`
`Time: HH:mm`

**Temperature and Duration**
`Temperature: X.YZ °C`
`Last data received: X minutes ago`

## Acceptance Criteria

- [ ] Something

**Comment by andreievg** [comment]
The logic for the cold chain notification is slowly creeping up in complexity, would it be ok for the Ok message to be an overall message, and maybe current temperature can be included in the template ?

**Comment by adamdewey** [comment]
Hmm, not sure how you can apply a generic message to 2 very different events 🤔 

`Alert resolved` ?

**Comment by andreievg** [comment]
This really brings up a lot of use cases:
* When ok and connection restored, we don't currently look if there was an excursion (or notify the user about it)
* When ok and temperature restored, does the user really need to go through all previous messages to figure out the excursions

If this notification system is really for real time monitoring, then the user will be well aware of what is wrong, wouldn't they ?

Otherwise the concept of 'breach' is more appropriate then excursion

**Comment by adamdewey** [comment]
To be honest, it might just be me, but having the 'Temperature ok' message was like a reassurance that the threshold limits are working. 

Louisa said the 'Temperature ok' message was unnecessary for her and that might be fair enough for the average end user. 

But I think the end user needs to receive the 'Monitoring ok' messages as it's kind of meta - like, is this Telegram notification channel that I'm looking at actually receiving anything from that sensor or has the connection gone down never to reappear? 

I also think it's worth noting that it might not just be people in the direct vicinity of the CCE / sensors that are monitoring the channels but also supervisors too, and so it could be helpful for them to see that things have returned to normal again (and to understand exactly what's returned to normal)

**Comment by andreievg** [comment]
Sounds like a scheduled report might help, a scheduled report for the sensor, every x hours for min, max and average temperature (could even add number of hours/minutes above/below threshold in that time period

**Comment by adamdewey** [comment]
Scheduled reports could definitely come in handy! But perhaps can park that for just now?

For these notifications I think if we can't separate the events then I would suggest we just don't provide an ok message for temperature excursion events resolving, and instead keep the ok message solely for the monitoring connection event? (and tailor the message for that event)

**Comment by adamdewey** [comment]
Note, I've updated the original description to remove ambiguity around separate messages for the alert resolved scenario. Will tackle that in a separate issue.
